### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsRLegacy#2]
@IndrajeetPatil Could you update the docs folder?

**Comment by IndrajeetPatil** [comment]
Update for what? The website is already updated:
https://esqlabs.github.io/esqlabsRLegacy/

**Comment by IndrajeetPatil** [comment]
Oh, I am guessing you mean update docs once the #1 has been merged.

**Comment by PavelBal** [comment]
yepp.

**Comment by IndrajeetPatil** [comment]
Can you please check if there are any other functions that are or are not supposed to be included here?

https://esqlabs.github.io/esqlabsRLegacy/reference/index.html
